import type { Metadata } from "next";
import {
  Big_Shoulders_Stencil_Text
} from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
const Stencil = Big_Shoulders_Stencil_Text({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ContactLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Stencil.className} antialiased bg-black`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
