import type { Metadata } from "next";
import {
  Big_Shoulders_Stencil_Text
} from "next/font/google";
import "../../../globals.css";


const Stencil = Big_Shoulders_Stencil_Text({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: "Register-Gymlink",
  description: "Generated by create next app",
};

export default function RegisterLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Stencil.className} antialiased bg-black`}
      >
        {children}
      </body>
    </html>
  );
}
